// 方向一手动开无头像61
const axios = require('axios');
const https = require('https');
const agent = new https.Agent({
  rejectUnauthorized: false // 设置为 false 表示不验证证书
});

const viewProtocol = `N4IglgJiBcIKwGMBGA2ALAMwKZILQEYAOONXJAQ3QIGZLctzCsUUMBOFCDakAGhAgBnADYwA2qAB2MECMhYATn1kxQFBAGsA5goD2AV0kQAwruG6lsAMQAGO/cI3lghFklYA8gAcALmF3S0KD6glgwGOTCoQC+0fwI4lIyLm5h/IKqIJLkALZhsIDv0YDJ8YCmioBc6oD2ZoCwKoAPnsqukj6KABowPgr6WPFuTQoAmm0dWHEgCdASWTJIugAezplgggBCs+GRoekGCq4yABY+Pl6C0AD0J15gCOSCgrq4gj7kfggAdDNg5Lq7AVqCu/ovBC6HLnBRYCAATxO+BsaBhACYwDZqDZJABHZFDHJoGwoNgAdl2ADdqGwkfYKfYFDYtBAIFh9MovMJyBDTI09KIgiByPofLoAAosiGDTr8cy6LxrKJdWTfADuABUIV58hEZfx6cLMiE1ethiMvLpBGA/AFMvypdAbOKsBgfDAbLE4klYEg+fzpOlMuQEGbAqAfCr8lksDMHSMfLssHlMuptHpDCYzBYZFYAGLp+FoNDw+opywgKwYEvKeM6AxGACSOXIWhDIEjYYd3KJkU6MkA016AZ2VAMpGgAB9ZQYAI+ADKYAAXvl8CgRmC/XGLPSFAAlcgQMAhGA4/jTA7AmDwlA22ST/LtMUgeWQKMwIhwfjRsBafbbp2xAC6LsmsBS7nm3LZLGhSlJUtT1D0LSirKDS9AM0AXsM8SJD+IDTHM3rcosKxzNA6obLIWw7LA+yHMcZwXFcNx3A8TyXG8HxfD8fwAkCIJeGCkLQrCCJIiikgKNmwgKFoeS4gSxKkuSlIUiJCBgF4WjkEywrsu0Zg+nygraghQzirokrSgRfy6EqwbQZqWA6cEoRGUhobhoqYDATZWBOXkBgtoh/B+MBKLvvwRomv6FqGdatr2o6zq8K6aEeuamGgL6IXckGqoyO44aNj50YuWhvoJpWybmIWGZZjmebxAWaYlhgZYFRWSY1nWDZNllrbtiGPYDkOI7jlOd6zvw84tmoS6KGuG5btAO5obo+45Iex7pGeFlXjeux3sQj5YM+r4ze+0RfjFqF/mkKiAbkIbFOU1R1N0jRQbpl6wYo8GISMYwTIEc0YRdoDYaseH6ps+jbCGpFHKc5yXNctz3I8zwMZ83ySL8/yAsCoLglCMJwjYiLIqiaL6KSABWzk4nihIkmSMmUn4dhEl4aAqayamcpp/JCqya0Sla+GyiZZnpcDGoCFZvPcrqdmxIFxqmv4AYgJajoRS2h0nT9OS6BAkQAaADwQsI+SBmFuBwCe5aJkYpglTVtWlruDU2xAzX1nsBxQxRsPUQjdGvO8KPMRjbEnNguDMk8w4KCC5A2OQWBwIQ8LIhASD4Ggdr4vi1AoK41BYPC8JYKX+JsHAXBsLi+eEPiLxeGjyjkJIzl0QEyqi7IVwm8oEBg+3gT+YF64bmjiphSiI90mAaMrAtMAopGpq99ytazzIgBYOoA+O6ANK2gCr0X3WAuDIVYeKO+b29YaD4vgluENlcX7sryVKxa5mwJlEbpAqSzxYEgsfIKAKooTIYYrSgDYjrSQAARJ4ylnqyj1o8cQx1RjCA0JkKBAQ4EoMQZqeBqDooq2clgTyOpbJixiJ9FCP024e0SoRMGxEQCQ3IjDKi8NaJIyDkxNGLFMYggjlHHwMcQT4lYEgHOTAbBsCQMQagCB4RwCQBABEddYQIDQBAQgaj8D4HxEgDABi2ANybsNLAC5uQmgGvg9aEBbzQCPNQHae0WyEEIM6Y6sV3TPwNjyP0b9Uofwct/FWuVTb5U0I1W21VrCZmzLmS+qZrC1XqtE127tWo+WbJkNswgOywG6oOfgw5Gj9WnENEAI1FwKGXJNTcGQDq7nmvyRaTjlqnlsd5exjj7yuJfC2HEXjvw/TOv4oC11QJ3Qgo9BQrQ7GvX6NBGh4wfGrEYYDXCgCmHg09mRaGlE4Y0URvRXhqN0asSxhxHG3F8aE34iTcmlNxI0ykvTCkjMbDM1ZoFVSI5Obcl5NzHSPT+Z2R/qZTuepxZailq5WWhoFYpTNlaE8JtIrWmirFHWetRCMKNqvVFMALZWxdkVO2KSiyOydlEwqTVawexIl7dhRy/bcLOYxC5Aiw7CJZKIiwccE5JxTmnDOWcMA5zzgXIuJcy4VyrjXBAdczFaGbq3Ws/poXJB7udfuwCUrDxAF4Ues8tATytFPY1pq56tIPNAJePkV6RPXj9HeB8j4n1gGfC+VUr5FhvnfGwD8Ri+M9D6QJ5pgldy/o/YWf8/FUNlO0EBlhQDgKwcCaBuCEE9OQQgsQaCEAYMzTkbNhC7H5qIXLEhHk+QUJhdQ5CazUL0POk0w2REIYssOb7LhpzA5cpDlcoRWBI78rEScaut8cCsAQBgQgd9b42B0fiTApd4TUAwFom+Nh8BYDYAumwC6UCquUDU6xq07HXgcZtDpLjWG7UGTADxIytZTH/v41+UbAwhOLcaMIkYIlxnJUmSlpUEkVWSaVNJzsMlFSyTIR+TR2qgHyYUkAgBT90AMoJgAwuV6uUq9M45yWNGnNOpE11yNLfC0heHSTw2PPHpXpd7+mPrcW+bFqFzAHDAGOm99YHQEq7fs72HDjn+x4UO/hodrmcVxjxAmfFib6BQPCJAWh0CvMknTD5dg0SEEODkIkvzjX/I5Bpbk4Kk2WR0k6dIQYiXGuRUE4l4UQAYo1iMRjmQb2OOoPiB87Hn3QEXfCZ0R1Rkfr8Yw79ys0ohn/bZIDMZInWwpXE6lGAZLQYdnVOD9LqyMu7Qcn2nCTkB2Rnwy5gjw5jpEZOlAhBkDkDYGwCAcJCDUCYDmXRa69ZtclQSGwDA2AIHayuwgeIz1tTI+hhspS+pXvs9U0jtT6lUemigWjbSX3ba6Uxy8fm71WqfCFx1PINWDwbQAQSuylQWIyvxAA`;
// const viewProtocol = `KJoKFZlRXFUMpUyWV5SDZVVW1dUsE1XTz0NG8zWgC0Hyfe0tSdF1XXdSZPW9FVpD9TkAxMzlQ3DGQEHMUIW34OMgLUANkxrNNzBLbNc3zQt4mLTNywwSt4urVN60bCMopAJpo0yTthG7WBAFP3QBlBMAMLlR3HKcL2gWd5ywRdOX3BQV3XTdt1fM8QH3Q9j1PGyoOvSBbw64hrVtFydzFWJP085CUncLCpFyCNinKao6m6RpIOgdorxgs64IuoY3W/ba/wyAD9pkQ7QJO67elaO6roaXoBj+4Zok/T8gA=`
const dslId = 81;

const edit = () => {
  axios
    .put('https://hawkeye.devops.xiaohongshu.com/api/marketing/container_render_rule', {
      rule: {
        id: dslId,
        name: '',
        viewProtocol
      }
    }, { httpsAgent: agent })
    .then((res = {}) => {
      const { data = {} } = res;
      const { success } = data;
      if (success) console.log(`更新盒子${dslId}成功!`);
    })
    .catch((error) => {
      console.log(`更新盒子${dslId}失败!`, error);
    });
};

edit();

