// 方向一手动开无头像61
const axios = require('axios');
const https = require('https');

const agent = new https.Agent({
  rejectUnauthorized: false // 设置为 false 表示不验证证书
});

const viewProtocol = "N4IglgJiBcIEwA4CMcBsAzVCC0AWBEAnNhLnMQOxzoAM2CZCArAMYDMApixwIbogAaEBADOAGxgBtUADsYIcZA4AnQQpigARjxYBrAObKA9gFcZEAMJGxR1bADENJ84Q0QAXyEsps+SO4yHGoiGiAALmBhYkGwgOAWgBkZagFhKgAaMGHKJhxeHDIpygCaGVkcniDe0NIgcrCaRgAewaEipsrc8gAWYWEADiLQAPSDvWAsPCKt2CJhPBEsAHQNYDxGnUYy+iKdJgssRgC2I8ocEACeg0g0uFdwYDRsNDIAjg+lB7g0qIQUnQBubEI92cIOcyho+ggEA4JjUYBEACFGiVskJemIeGcrPljBJoKAeCYwkYAAoYs4onIgGxGXowdA8MQiKnbIwAdwAKmdejEGUyqdDyaETMz6Yzme5yr0jCJImANqFiXToDQhNF0GEYDRJZ5fLARSpsGAZOgjM18eFaTA4E4hGMFdA+cyhDIeAcYqBWWyxfyhDwoRsERxTSd5AAJDhnQAw/2p/RANgBBDUqeQAPw8Qmh/nkgFsDQA5qoB24MA6fqABtNAF1ygA4lDy6mryXondAcMIsTrmgmjeSDHijQYHHjKXRN436QYcBpcInymQAfRmyjmHH0F2AY4nEQ2AEkIO41NpmQBVABKABkuj1+kNRxBIp0lis1hstjs9oc1GFuTEQPom2pev23SEVSgO+PJ+Jkw5qH8jLZKE6DGAc8gmMoEhCDMcxjAAatBn5qHBhwANKRvIq4sJOm5QOUg4UrAJFkTIW4eAAupKAh6iAmhEsScioaEOjrrUwEfvIgQNJq5RhJ0HDuqE2h6IYpjmFYNh2CA9gAGJqXAuBkEk1i2PI9joEZu46AYxhmBAG59t+8gZuEY6ahaUFiDBsCANNegDOyoAykaAAD6uEbGEADKYAAF4xEgqDlCcLCOVotjQsoh7+mAIowJ8Qj1D0r7QGgqoKKFMSZKiIBspAEkwEgzBCJJYD6N0aXaixbEcVl3HqBafFToqQmwCJYlCBJUkeuxpnyRZSn6Q4Rmgm4Xh6SphlGUtTgmXJ5nmFZPA2bAdkpKJoTOa5ID+fkwVhRVcBRVwsXsfFKhJdeqXQKgGVGFlCE5TcqEFZSQilRA5XQGwFBMNVHC1fVOWEI17jMaxtawP4eRBDxFoRFEn4JEkeQFOk0BFVSyQqMU+OlOUlTVLUt1NKjnptB0sDdH0AzDKM4yTEY0yzPMd6rOsmzbLs+xHPWpwXFcNw0HcDxPMoWliMo+jul8Pz/ICwIzWC+gsGAvT6DwcKIsipPFeimLYpk1i8USpJCibVI0sqTosusnI9QTmYcHboAGj6Eoug5HJgNJFoGkH7qmI5HvhMHMSPI1aIynKDrAVaKpqsGjkw/DVMGsoRommatOWsqNp5fatTOy6brDV6ftUnGgbBrYn4RtGsYBjISYFGmdlZpUID5sW5ZVk1CPsZxCrF51KfhD1NQmGIEjiZJIdaKN62WPNBkaVpOlzcpBlLatZkKZZ1k4eJDkHdh8ieb5J1BT90ARVdMUyXdiXJU96W3e91qoDyrKc69s/plVbC/KqIAap1Ucp8HUcM2JI0CG2GoNdQhuFgIAd+i1BIHkIAZPi1BwHkIAU0U1BsHkIALnU1C4HkIAezM1BMHkIAWBU1CoHkIAB89giu1+iARuMggwhlbpGGMfpO7dxTLAdM5McZpF4UTIo9dyY+HHvUGm7U6ZIQZtA88LMRhjAmFMNCPNlh80fILF8IsTjnEuNcW49xHhGA4BwXQEATgUH0CrX4AIgSaxBMoTQYQZBwA4CEO0RsmiOnFFSM2WIAq4mtsSMkmJeGO3rqhV2XJQJRN9MIL2KTQ6ilATHEO8cWIgGlLKfiio055XVFnHUOd5AHCMBARkqCZhnGiDU0utoRprTPhNBaS1j4ZQ3mfTa20dHM0vGzQxnNjFjF5g+AWz5haDEbNgM2YQQxHB4DQHgHAmAIBtGwCAmgkC4GDBQCgbBUDcE4HAEJziKCECYBAdA0NUD3IQBQBYvRNixhkMHdCGwsmfn8IyFGwgkKgtqHAJg2oBqRG6RaPsxpcyFlLJWNQ/d5CAAtFQAznqAAflQAYqqAEGVQA98qAApXXSh8HC4AoEgRFCA7ItS4rxGKXU0bzxYDYUU5QvQIknrUaOe1HIgEAKfugBlBMAGFyJ8xqKW3g4Xe2liFjIGRZSZOED6TVUqMkAppTrP0ueJWOkdhRFOduJecehJGem5k9EAeDykUzYvsEw0oZDYECN6YuIFPx8B7hq0+WqL5nhmazAxHMuboUWKYlZT4haHA2RwLZGIdm2COJoBA6AoQUAQJoFgTAbiYCQMDe5PAEBsDOagJAFAjI3MIBwA5wMIAPH+YCoQfZFbGiRP/HKjVEHjxsD0MAab/rfk1MXVoWjPxMwvFG9mRjuZLITfzJNljjhi1sZLaWjjdBMiMIemg9xvjePVn45wvROi6AAFa6BYLNCp5ILYJItGknJzo8l2yRQod8qLQCVOTgJEuF06mZy1IK5+oB/qA2BqDaB4NYHWhtDqWGNYqYqGMPnP8Nli4gqmQuvRzxg76GWRuix6y/jGmSNgf0BxjSDEQJodAmgKBOBrQi15NAmBwE0BwbS7beM0AgOwY5uBi1MB0LcoIY8qbsqnhovhXLZ4BvkHymUcmBqr2GrJUNSr6X6toKCOlerFr8BDYq8+W1526NmdGldcaKPmLWSmzZ2zdmDCwCwbQhBCCkEqmwBAgn8AQAoLgNp/n0CvI47wQgLAAuiYQN8Tt+hdrXycrfHaQgjVPxAX+6KN16jKASg9FKgEXp/2JB9FL30QHRzgxAx4YMIaOUeOUHgwK+zVMKRwBM3W4VKMlMxZiQA==";

const edit = () => {
  axios
    .put('https://hawkeye.devops.xiaohongshu.com/api/marketing/container_render_rule', {
      rule: {
        id: 73,
        name: '给文杰',
        viewProtocol
      }
    }, { httpsAgent: agent })
    .then((res = {}) => {
      const { data = {} } = res;
      const { success } = data;
      if (success) console.log('编辑盒子【手动开无头像】成功!');
    })
    .catch((error) => {
      console.log('编辑盒子【手动开无头像】失败!', error);
    });
};

edit();

